server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 这个是入驻eureka注册中心的开关，不想入驻就改为false
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka